# SPLIT TEST
root_dir: output/
# Variables that are global to all your stages
# and their values
globals:
  savename: "f090nilc"
  random: False
  save-filtered-catalog: True
  catalogue: "full_catalog_Y3_no_src_with_cluster_mask.txt"
  cmb: "/project/rrg-rbond-ac/msyriac/ilc_dr6v3/20230606/ilc_fullRes_TT_smallScale_f090.fits"
  #mask: "/home/jiaqu/Thumbstack_DESI/wide_mask_GAL070_apod_1.50_deg_wExtended_srcfree_Will.fits"
  #mask: "/project/rrg-rbond-ac/msyriac/ilc_dr6v3/20230606/wide_mask_GAL070_apod_1.50_deg_wExtended.fits"
  mask: "/home/jiaqu/Thumbstack_DESI/output/wide_mask_GAL070_apod_1.50_deg_wExtended_no_src_with_cluster.fits"


gitcheck_pkgs:
  - numpy
  - scipy



stages:

  stage_profile:
    script: test.py
    exec: python
    globals:
      - savename
      - random
      - catalogue
      - cmb
      - mask
      - save-filtered-catalog
    parallel:
      nproc: 120       # 15 nodes * 12 tasks per node
      threads: 16     # 16 CPUs per task
      walltime: 00:15:00

  stage_bootstrap:
    script: test_cov.py
    exec: python
    depends:
      - stage_profile
    globals:
      - savename
      - random
      - catalogue
    parallel:
      nproc: 480       # 30 nodes * 16 tasks per node
      threads: 16     # 16 CPUs per task
      walltime: 00:15:00









